image: docker:latest

variables:
  DOCKER_HOST: 'unix:///var/run/docker.sock'

before_script:
  - docker info

stages:
  - build

build:
  stage: build
  script:
    - docker build -t cms-frontend-manage:latest .
